server.port=8090

spring.application.name=Patient-service
logging.level.root=info

## H2 for testing only
#spring.h2.console.path=/h2-console
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=root
#spring.datasource.password=admin
#
#spring.jpa.hibernate.ddl-auto=update
##spring.sql.init.mode=always
#spring.jpa.defer-datasource-initialization=true
#
## KAFKA CONFIG FOR DOCKER
#spring.kafka.bootstrap-servers=localhost:9094
##spring.kafka.bootstrap-servers=kafka:9094
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.ByteArraySerializer