server.port=8090

spring.application.name=Patient-service
logging.level.root=info

#UNCOMMENT THIS CODE OUTSIDE DOCKER- USE IN MEMORY DATABASE
#spring.h2.console.path=/h2-console
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=root
#spring.datasource.password=admin


spring.jpa.hibernate.dll-auto=update
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true



spring.kafka.bootstrap-servers=kafka:9092

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.ByteArraySerializer